[package]
name = "torrust-tracker"
version = "0.9.1"
authors = ["Mick van Dijke <mick@dutchbits.nl>", "Naim A. <naim@abda.nl>"]
description = "A feature rich UDP based BitTorrent tracker."
edition = "2018"

[profile.release]
lto = "fat"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
warp = {version = "0.3", default-features = false}
tokio = {version = "1.7", features = ["macros", "io-util", "net", "time", "rt-multi-thread", "fs", "sync", "signal"]}
binascii = "0.1"
toml = "0.5"
clap = "2.33"
log = {version = "0.4", features = ["release_max_level_info"]}
fern = "0.6"
chrono = "0.4"
byteorder = "1"
external-ip = "4.1.0"
r2d2_sqlite = "0.16.0"
r2d2 = "0.8.8"
rand = "0.8.4"
