[package]
name = "torrust-tracker-test-helpers"
description = "A library providing helpers for testing the Torrust tracker."
license = "AGPL-3.0"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lazy_static = "1.4"
rand = "0.8.5"
torrust-tracker-configuration = { version = "3.0.0-alpha.1", path = "../configuration"}
torrust-tracker-primitives = { version = "3.0.0-alpha.1", path = "../primitives"}
