[package]
description = "A library to provide configuration to the Torrust Tracker."
keywords = ["config", "library", "settings"]
name = "torrust-tracker-configuration"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
config = "0.13"
log = { version = "0.4", features = ["release_max_level_info"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.2"
thiserror = "1.0"
toml = "0.8"
torrust-tracker-located-error = { version = "3.0.0-alpha.11-develop", path = "../located-error" }
torrust-tracker-primitives = { version = "3.0.0-alpha.11-develop", path = "../primitives" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
