[book]
authors = ["Naim A.", "Mick van Dijke"]
title = "Torrust Tracker v1"
description = "Torrust Tracker v1 Documentation"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/torrust/torrust-tracker"
default-theme = "coal"

[output.html.search]
enable = false
