[package]
description = "A library with the primitive types shared by the Torrust tracker packages."
keywords = ["api", "library", "primitives"]
name = "torrust-tracker-primitives"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
derive_more = "0"
thiserror = "1"
binascii = "0"
serde = { version = "1", features = ["derive"] }
tdyne-peer-id = "1"
tdyne-peer-id-registry = "0"